// Legend text (object, sound) per letter token -- for the pictographic
// keyboard's hover tooltip. Hand-synced from 00-laws.md's census, the same
// way letters.js's spoke/ring tables are, rather than parsed from the
// markdown at runtime. Keep in step with the census by hand when it changes.
// REST is deliberately absent -- it's an engine device (see letters.js),
// not a census entry, and isn't shown as a keyboard key at all.
export const LEGEND_OF = {
  I: { object: "ice / plumb", sound: "i" },
  O: { object: "eye / witness", sound: "o" },
  N: { object: "nail", sound: "n" },
  "ŋ": { object: "K-place + N-manner (open ligature)", sound: "ŋ" },
  M: { object: "square / mouth", sound: "m" },
  K: { object: "key", sound: "k" },
  T: { object: "mark-bearer", sound: "t" },
  B: { object: "bed / beth, the shelter (the Living Bed)", sound: "b" },
  G: { object: "key (K's rotation-twin)", sound: "g" },
  D: { object: "mark-bearer (T's rotation-twin)", sound: "d" },
  P: { object: "bed / beth (B's rotation-twin)", sound: "p" },
  L: { object: "Rocko / Leo -- leads, couchant", sound: "l" },
  H: { object: "hook (Y's flip-twin)", sound: "h" },
  "H.c": { object: "hook family (mark on H)", sound: "ç" },
  "H.x": { object: "hook family (mark on H)", sound: "x" },
  R: { object: "Rocko / Leo -- returns, sejant erect", sound: "r" },
  Y: { object: "yellow / fork", sound: "j" },
  S: { object: "string / sign", sound: "s" },
  SH: { object: "shore (field-forced by Djyash)", sound: "ʃ" },
  V: { object: "fold / folio (·v reading)", sound: "v" },
  F: { object: "fold / folio", sound: "f" },
  Z: { object: "string / sign (S's rotation-twin)", sound: "z" },
  ZH: { object: "shore (SH's rotation-twin)", sound: "ʒ" },
  "TH": { object: "congruent Greek borrow (theta)", sound: "θ" },
  "DH": { object: "Greek borrow, mark reading (eth)", sound: "ð" },
  CH: { object: "shore + stop-mark", sound: "tʃ" },
  JH: { object: "shore + stop-mark, rotated", sound: "dʒ" },
  W: { object: "wave", sound: "w" },
  E: { object: "door", sound: "e" },
  A: { object: "axe", sound: "a" },
  "vowel.horizontal": { object: "earth prime (no object/token authored yet)", sound: "" },
  "vowel.nub": { object: "heaven prime (no object/token authored yet)", sound: "" },
  "OE": { object: "E+O vowel ligature (L8/G-A2)", sound: "ə (schwa)" },
  "EA": { object: "E+A vowel ligature (L8/G-A2)", sound: "æ" },
  "OO": { object: "O+O vowel ligature (L8/G-A2)", sound: "u" },
  "AE": { object: "A+E vowel ligature -- G-A2's own cited example", sound: "eɪ" },
  "AI": { object: "A+I vowel ligature", sound: "aɪ (as in \"eye,\" \"my,\" \"time\")" },
  "AO": { object: "A+O vowel ligature -- retired /ʌ/ (now OE's job too), reused for the diphthong", sound: "aʊ (as in \"cow,\" \"how,\" \"now\")" },
  "OI": { object: "O+I vowel ligature", sound: "ɔɪ (as in \"boy,\" \"toy\")" },
};
